Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,6 +13,23 @@ include:
     ref: v0.2.0
     file: recommender/Reviewers.gitlab-ci.yml
 
+check scanner version:
+  stage: test
+  image: docker:20.10
+  script:
+    - |
+      SCANNER_VERSION=$(egrep -o "SCANNER_VERSION(?:=|:-){1,}([a-zA-Z0-9.-_]+)" Dockerfile)
+      SCANNER_VERSION_FIPS=$(egrep -o "SCANNER_VERSION(?:=|:-){1,}([a-zA-Z0-9.-_]+)" Dockerfile.fips)
+      # check if SCANNER_VERSION is the same as SCANNER_VERSION_FIPS
+      if [ "$SCANNER_VERSION" != "$SCANNER_VERSION_FIPS" ]; then
+        echo "Error: SCANNER_VERSION and SCANNER_VERSION_FIPS are not the same."
+        exit 1
+      fi
+  rules:
+    - if: '$REPORT_FILENAME == "gl-sast-report.json"
+      exists:
+        - 'Dockerfile.fips'
+
 reviewers-recommender:
   stage: pre-build
   rules:
